### ISSUE TITLE
Making the README.md file look better.

### ISSUE THREAD

**Issue by glaukiol1** [glaukiol1/G-script#3]
Anyone can contribute to this project, for this issue, people can work on making the overall design of of the README.md file better. You can add more descriptive guides on installing and running, more details on the docs, and more!

Thanks!

**Comment by aditya28sarin** [comment]
Hey, can you assign this issue to me?

**Comment by glaukiol1** [comment]
Of course, let me do it right now

**Comment by glaukiol1** [comment]
#5
